# Generated by Django 5.2.6 on 2025-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='api_url',
            field=models.URLField(default='https://example.com/dummy'),
        ),
    ]
