# Generated by Django 5.2.6 on 2025-11-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_municipality_alter_post_options_alter_post_title_and_more'),
        ('notices', '0004_uploadedpdf'),
    ]

    operations = [
    ]
